// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// crtTest
double crtTest(double test);
RcppExport SEXP _tburden_crtTest(SEXP testSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type test(testSEXP);
    rcpp_result_gen = Rcpp::wrap(crtTest(test));
    return rcpp_result_gen;
END_RCPP
}
// c_uti_surv
double c_uti_surv(NumericMatrix surv_f);
RcppExport SEXP _tburden_c_uti_surv(SEXP surv_fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type surv_f(surv_fSEXP);
    rcpp_result_gen = Rcpp::wrap(c_uti_surv(surv_f));
    return rcpp_result_gen;
END_RCPP
}
// c_pseudo_response
NumericVector c_pseudo_response(NumericVector pchg, double thresh_cr, double thresh_pd);
RcppExport SEXP _tburden_c_pseudo_response(SEXP pchgSEXP, SEXP thresh_crSEXP, SEXP thresh_pdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pchg(pchgSEXP);
    Rcpp::traits::input_parameter< double >::type thresh_cr(thresh_crSEXP);
    Rcpp::traits::input_parameter< double >::type thresh_pd(thresh_pdSEXP);
    rcpp_result_gen = Rcpp::wrap(c_pseudo_response(pchg, thresh_cr, thresh_pd));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tburden_crtTest", (DL_FUNC) &_tburden_crtTest, 1},
    {"_tburden_c_uti_surv", (DL_FUNC) &_tburden_c_uti_surv, 1},
    {"_tburden_c_pseudo_response", (DL_FUNC) &_tburden_c_pseudo_response, 3},
    {NULL, NULL, 0}
};

void my_package_init(DllInfo *dll);
RcppExport void R_init_tburden(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    my_package_init(dll);
}
