# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crtTest <- function(test) {
    .Call(`_tburden_crtTest`, test)
}

c_uti_surv <- function(surv_f) {
    .Call(`_tburden_c_uti_surv`, surv_f)
}

